# Use the official .NET Core SDK image to build the application
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

# Copy the project file and restore dependencies
COPY SampleWebapi/*.csproj .
RUN dotnet restore

# Copy the rest of the application code and build the application
COPY SampleWebapi/ .
RUN dotnet build

#run ef and gen script
RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"
RUN dotnet ef dbcontext script -o out/init.sql
